config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "user/registrations"}

  root 'welcome#index'
  get 'my_menu', to: 'menu#new'
  post 'save_products', to: 'menu#save'
  delete 'products', to: 'menu#destroy'

end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :user_food_type
  has_many :food_grids

  monetize :price_cents
end

app/models/food_grid.rb
class FoodGrid < ActiveRecord::Base
  belongs_to :food
end

app/models/food_type.rb
class FoodType < ActiveRecord::Base
  has_many :user_food_types

  has_many :foods, through: :user_food_types
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_food_types
  has_many :food_types, through: :user_food_types
end

app/models/user_food_type.rb
class UserFoodType < ActiveRecord::Base
  belongs_to :user
  belongs_to :food_type

  has_many :foods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def new
    @user = current_user
  end

  def save
    if params[:id] and params[:id] != ""
      food = Food.find(params[:id])
      params[:price] = params[:price].gsub('.', '').gsub(',','.')
      if food.update(params.permit(:price,:name))
        redirect_to my_menu_path, notice: "Food was successfully updated."
      else
        redirect_to my_menu_path, flash[:error] = "There was an error with updating food."
      end

    else
      food = Food.new(name: params[:name],
                      price: params[:price].gsub('.', '').gsub(',','.'),
                      user_food_type: UserFoodType.find(params[:user_food_type]))
      if food.save
        respond_to do |format|
          format.html { redirect_to my_menu_path, notice: "Food was successfully added." }
        end
      else
        redirect_to my_menu_path, flash[:error] = "There was an error with adding food."
      end
    end
  end

  def destroy
    food = Food.find(params[:id])
    food.destroy
    respond_to do |format|
      format.html { redirect_to my_menu_path, notice: "Food was successfully removed."}
    end
  end

end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address, :phone, :is_restaurant])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :address, :phone])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Restaurants" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Restaurants</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/menu/_modal.html.erb
<div id="product_modal" role="dialog" class="modal fade" tabindex="-1" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Product</h4>
        <div class="modal-body">
          <div id="food-error">
          </div>
          <%= form_tag save_products_path, remote: true, id: 'food-form-modal' do %>
            <%= hidden_field_tag :id, params[:id] %>
            <%= hidden_field_tag :user_food_type, params[:user_food_type]%>
            <div class="form-group">
              <%= label_tag :name%>
              <%= text_field_tag :name, params[:name], placeholder: 'Product name', autofocus: true, class: 'form-control' %>
            </div>
            <div class="input-group">
              <span class="input-group-addon">R$</span>
              <%= text_field_tag :price, params[:price], placeholder: '0,00', class: 'form-control', data: { role: 'money', a_sep: '.', a_dec: ',' } %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
              </button>
              <%= button_tag(type: :submit, class: 'btn btn-success') do %>
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
              <% end %>
            </div>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/menu/new.html.erb
<div class="list-group" id="menu-div">
  <div class="list-group-item">
    <% @user.user_food_types.each do |user_food_type| %>
      <div class="list-group">
        <div class="food_type">
          <label>
            <%=	user_food_type.food_type.name %>
          </label>
        </div>
        <div class="btn-group btn-group-sm btn-food" role="group">
          <button type="button" class="btn btn-default" data-toggle="modal" data-target="#product_modal"
                  data-type=<%=user_food_type.id%>>
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
          </button>
        </div>
        <% user_food_type.foods.each do |food| %>
          <div class="list-group-item">
            <div class="food">
              <label>
                <%= food.name %>
              </label>
            </div>
            <div class="btn-group btn-group-sm" role="group">
              <button type="button" class="btn btn-default" data-toggle="modal" data-target="#product_modal"
                      data-name="<%=food.name%>" data-id="<%=food.id%>" data-type="<%=food.user_food_type_id%>"
                          data-price="<%=food.price%>">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
              </button>
              <%= link_to products_path(:id => food.id), :method => :delete,
                          :data => {:confirm => "Are you sure?"},
                          :class => "btn btn-xs btn-danger" do%>
                  <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
              <% end %>
              <!--<button type="button" class="btn btn-default">
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
              </button>-->
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= render 'modal' %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to the restaurant app</h1>

<%= link_to "logout", destroy_user_session_path, method: :delete %>